### ISSUE TITLE
jobs start but are left in (I) state.

### ISSUE THREAD

**Issue by peteasa** [earonesty/grun#7]
I have an embedded system and have build grun plus perl modules required.  Most of this seems to work except that jobs do not complete ie I run grun hostname and it never returns .. i have to kill the job
`
$ grun -q jobs
29  pas (I) /home/pas   hostname
28  pas (I) /home/pas   hostname
`
job 29 was started on the remote exec system, job 28 was started on the local queue system.  Both systems have same user name, user id and group id, just in case that makes a difference
`
Fri Oct 21 16:12:50 2016    trace   Received command (00b6b854d6) 'run' : ["192.169.0.118",null,"run",{"umask":2,"env":{"USER":"pas","PATH":"/home/pas/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"},"frompid":22264,"guid":"D517E09497A011E69D75A4AA68EA6766","syncdirs":["/home/pas"],"io":1,"hard_factor":null,"user":"pas","param":{},"group":"1000 4 20 24 46 104 111 119 122 124 137 1000","cwd":"/home/pas","wait":1,"memory":"1000000","cmd":["hostname"],"priority":"20","cpus":1}] 
`
wireshark shows ping packets working ok.

Perhaps some security issue stops the job being run on the remote system??  Or something like that?  I cant see any good logs from tracing on the exec system.. all it seems to show is start and stop of the daemon.. I find that odd .. perhaps also I have some problems with building all the necessary perl modules on my embedded system..  anyway even with no logs on the embedded (exec) side both sides seem to get the idea that the job is started as shown above.. 

This must be finger trouble but as I am new to this I cant work out why it is not working.  Hope you can help

Built the libraries on a laptop and a desktop and it works!  Still no luck with the embedded processor.. still having problems but at least I can now see how it should work!

Peter.

**Comment by peteasa** [comment]
I think that my problem is DNS.  I now have three machines A, and B are both on DNS but the embedded machine E is not. I have mDNS running so all machines can be reached using ping A.local, B.local, E.local.  At startup assuming A is the queue host both B and E both talk to A and in this exchange A discovers the IP address of B and E.  However when the grun hostname is started, A attempts to find a suitable machine, but uses DNS to locate the machine.  This is a shame because at this point A already knows the IP address of all the machines.  Anyway in my case because E is not on DNS it is on mDNS A cant find a machine and the grun hostname task hangs.

Pity mDNS ie hostname.local as well as normal DNS is not used for the lookup!
Peter

**Comment by peteasa** [comment]
Made a bit more progress.. now I have patched mDNS support..  looks like the default memory size was no good for embedded hardware.  Reduced this.  Now I get more logs on the embedded side
`
Thu Oct 20 17:06:11 2016        trace   Received command (00b6b85476) 'xexec' : ["192.169.0.118","1","xexec",{"param":{},"memory":"10000","version":"0.9.15872","group":"1000 27 1000","wait":1,"priority":"20","hard_factor":null,"syncdirs":["/home/pas"],"id":"23","cpus":1,"time":1477151517,"trace":"1","guid":"8055419696E711E6B34D3B2591D4F24B","cmd":["hostname"],"frompid":672,"umask":18,"fromip":"192.169.0.106","io":1,"cwd":"/home/pas","user":"pas","file":"/var/spool/grun/jobs/23","env":{"PATH":"/usr/local/bin:/usr/bin:/bin","USER":"pas"},"port":"5184"}]
Thu Oct 20 17:06:11 2016        note    Started job 23, pid 682, 'hostname'
Thu Oct 20 17:06:11 2016        trace   Received command (00b6b85496) 'xio' : ["192.169.0.106",null,"xio","23"]
Thu Oct 20 17:06:11 2016        debug   Creating io_wait hash entry for 23, (E:, )
Thu Oct 20 17:06:11 2016        debug   PGID set to 682
Thu Oct 20 17:06:11 2016        debug   Wrote /var/spool/grun/jstat/23.sh
Thu Oct 20 17:06:11 2016        debug   Setting uid to 1000, gid to 1000 27 1000.
Thu Oct 20 17:06:31 2016        trace   Received command (00b6b85496) 'xio' : ["192.169.0.106",null,"xio","23"]
Thu Oct 20 17:06:51 2016        trace   Received command (00b6b85496) 'xio' : ["192.169.0.106",null,"xio","23"]
Thu Oct 20 17:06:57 2016        debug   Reply (00b6b85496) ["23:stat",{"status":-8,"dumped":1,"id":"23","error":"Unknown 23 exit code, really bad!"}]
Thu Oct 20 17:06:57 2016        debug   Notifying status {"status":-8,"dumped":1,"id":"23","error":"Unknown 23 exit code, really bad!"}.
Thu Oct 20 17:06:57 2016        trace   Received command (00b6b85496) 'xclean' : ["192.169.0.106",null,"xclean","23"]
Thu Oct 20 17:06:57 2016        debug   Client is finished with 23
Thu Oct 20 17:06:57 2016        trace   Received command (00b6b85476) 'dack' : ["192.169.0.118","1","dack","jid","23"]
Thu Oct 20 17:06:57 2016        debug   Got dack for 23
Thu Oct 20 17:06:57 2016        debug   Cleaning 23
`
`
$ grun hostname
[parallella-hdmi.local] Unknown 23 exit code, really bad!
`

**Comment by peteasa** [comment]
Now working ... with one exception. I can provide the patch for mDNS if you would like.

The one problem now seems to be a timing related issue.  the embedded system goes into a tight loop.  I can "fix" this with a call to a system function after the init(); in grun:
`
init();
system("echo after init >> /dev/null");
`
Without this system call the tight loop produces the following in the log file:
`
Thu Oct 20 22:24:34 2016	trace	Received command (00b6b854b6) 'stream' : ["192.169.0.106",null,"stream","41:out","parallella-hdmi\n"] 
Thu Oct 20 22:24:34 2016	trace	Received command (00b6b854b6) 'stream' : ["192.169.0.106",null,"stream","41:out","parallella-hdmi\n"] 
`
the processes running on the embedded system are:
`
 5302 root     67748 R    {grun} /usr/bin/perl /usr/bin/grun -d -t
 5315 pas      65364 R    /usr/bin/perl /usr/bin/grun -C /etc/grun.conf -X 0.0.0.0:5184 29:out
`
And I have to abort the grun hostname command:
`
$ grun hostname
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
parallella-hdmi
^CAborting command, sending jkill for 41
`

Not very good to have this race condition .. I am guessing that because I am running the grun on an embedded system the timing is different and the race condition is observed.  Anyway as I mentioned I can provide the following mDNS fix for you as a patch if you like.

Peter.


`
sub raw_host2ip {
  my (@octets, $raw_addr, $ip);
  return $_[0] if $_[0] =~ /^(\d+\.){3}\d+$/;
  $raw_addr = (gethostbyname($_[0]))[4];
  @octets = unpack("C4", $raw_addr);
  $ip = join(".", @octets);
  return($ip);
}

sub host2ip {
  my ($test_addr, $tmpstr, $mDNSdomain);
  return $_[0] if $_[0] =~ /^(\d+\.){3}\d+$/;
  $test_addr = raw_host2ip($_[0]);
  if (!$test_addr) {
    $mDNSdomain = '.local';
    if (length $_[0] > length $mDNSdomain) {
      $tmpstr = substr($_[0], -(length $mDNSdomain));
      if (!($tmpstr eq $mDNSdomain)) {
        $test_addr = raw_host2ip($_[0] . $mDNSdomain);
      }
    } else {
      $test_addr = raw_host2ip($_[0] . $mDNSdomain);
    }
  }

  return ($test_addr);
}
`

**Comment by earonesty** [comment]
I would merge this patch.

**Comment by peteasa** [comment]
Let me know if you get the same hang problem.. if  so I can provide the patch with the system call that seems to avoid the hang issue..  The system call is added just after the call to init()
`
init();
system("echo after init >> `/dev/null");`
my $stream_quit = 0;
`

**Comment by earonesty** [comment]
merged in the echo as well.   it can't hurt.  i suspect it's a tty thing.
